services:
  frontend:
    build:
      context: './frontend'
      network: host
    environment:
      - MONGO_DB_URL=${MONGO_DB_URL}
      - S3_ACCESS_ID=${S3_ACCESS_ID}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
    ports:
      - "5173:5173"
  backend:
    build: './backend'
    ports:
      - "5174:5173"
    environment:
      - MONGO_DB_URL=${MONGO_DB_URL}
      - S3_ACCESS_ID=${S3_ACCESS_ID}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - AUTH_SECRET=${AUTH_SECRET}
      - ORIGIN=${DEVBE_ORIGIN}
      - AUTH_TRUST_HOST=true
    volumes:
      - type: bind
        source: './backend'
        target: '/usr/src/app/'
      - type: volume
        source: exclude
        target: '/usr/src/app/node_modules'

  nginx:
    build: './nginx-dev'
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - frontend

volumes:
  db_data:
  exclude: