services:
  frontend:
    build:
      context: './frontend'
      network: host
    ports:
      - "5173:5173"
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - db_data:/data/db

  nginx:
    build: './nginx'
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  db_data: