services:
  frontend:
    build:
      context: './frontend'
      network: host
    ports:
      - "5173:5173"
  backend:
    build: './backend'
    ports:
      - "5174:5173"
    volumes:
      - type: bind
        source: 'C:\Users\alex.crease\Documents\Git\Hierophant\backend'
        target: '/usr/src/app/'
      - type: volume
        source: exclude
        target: '/usr/src/app/node_modules'
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - db_data:/data/db

  nginx:
    build: './nginx'
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - frontend

volumes:
  db_data:
  exclude: