services:
  frontend:
    image: 'apolloxiv/frontend'
    ports:
      - "5173:5173"

  backend:
    image: 'apolloxiv/backend'
    ports:
      - 5174:5173

  nginx:
    image: 'apolloxiv/nginx'
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    volumes:
      - type: bind
        source: /etc/ssl/
        target: /etc/ssl/
