services:
  frontend:
    image: 'apolloxiv/frontend'
    ports:
      - "5173:5173"
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - db_data:/data/db

  nginx:
    build: 'apolloxiv/nginx'
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  db_data: