services:
  frontend:
    image: apolloxiv/frontend
    environment:
      - MONGO_DB_URL=${MONGO_DB_URL}
      - S3_ACCESS_ID=${S3_ACCESS_ID}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
    ports:
      - "5173:5173"

  backend:
    image: apolloxiv/backend
    environment:
      - MONGO_DB_URL=${MONGO_DB_URL}
      - S3_ACCESS_ID=${S3_ACCESS_ID}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - AUTH_SECRET=${AUTH_SECRET}
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
      - AUTH_TRUST_HOST=true

    ports:
      - 5174:5173

  nginx:
    image: apolloxiv/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    volumes:
      - type: bind
        source: /etc/ssl/
        target: /etc/ssl/
