name: Deploy Webapp to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-frontend-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: apolloxiv
        password: ${{ secrets.DOCKER_HUB_API_KEY }}
      
    - name: Build and push the Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./frontend
        tags: apolloxiv/frontend
        push: true
        
  build-backend-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: apolloxiv
        password: ${{ secrets.DOCKER_HUB_API_KEY }}
      
    - name: Build and push the Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./backend
        tags: apolloxiv/backend
        push: true
        
  build-nginx-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: apolloxiv
        password: ${{ secrets.DOCKER_HUB_API_KEY }}
      
    - name: Build and push the Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./nginx
        tags: apolloxiv/nginx
        push: true

# Create .env file in /deploymentPackage/

  create-environment-file:
    runs-on: ubuntu-latest
    steps:
    - name: Create .env file
      run: touch ./deploymentPackage/.env
    - run: echo "${{ secrets.ENV_FILE }}" > ./deploymentPackage/.env

# Copy prod.yml to /deploymentPackage/docker-compose.yml
  copy-compose-file-to-deploy-pkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cat prod.yml > ./deploymentPackage/docker-compose.yml

# Upload deploymentPackage/ to webserver using web-deploy

  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.ENV_IP_ADDR }}
          remote-user: ec2-user
          private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          destination-path: ~/pkg/

# WAIT FOR ALL OTHER JOBS TO FINISH

  activate-package:
    runs-on: ubuntu-latest
    needs: [build-nginx-and-push, build-frontend-and-push, build-backend-and-push, web-deploy, copy-compose-file-to-deploy-pkg, create-environment-file,]
    steps:
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: run package
      run: sudo sh ~/pkg/up.sh
