name: Build & Push Images to Docker Hub

on:
  push:
    branches:
      - main

jobs:

  build-frontend-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: apolloxiv
        password: ${{ secrets.DOCKER_HUB_API_KEY }}
      
    - name: Build and push the Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./frontend
        tags: apolloxiv/frontend
        push: true
        
  build-nginx-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: apolloxiv
        password: ${{ secrets.DOCKER_HUB_API_KEY }}
      
    - name: Build and push the Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./nginx
        tags: apolloxiv/nginx
        push: true
  
  pull-images-and-run:
    runs-on: ubuntu-latest
    environment: empress-1
    needs: [build-nginx-and-push, build-frontend-and-push]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: run compose on remote
      run: DOCKER_HOST="ssh://root@${{ vars.ENV_IP_ADDR }}" docker compose up
# update
